
    export const products =[
        {
            name:"Banana",
            quantity:1,
            type:"Fruit",
            price:450,
            image:"https://i.postimg.cc/mkLmyJXC/banana.jpg"
        },
        {
            name:"Berries",
            quantity:1,
            type:"Fruit",
            price:450,
            image:"https://i.postimg.cc/bYVx5ZdK/berries.jpg"
        },
        {
            name:"Melon",
            quantity:1,
            type:"Fruit",
            price:450,
            image:"https://i.postimg.cc/Y90JCJW0/melon.jpg"
        },
        {
            name:"Ginger",
            quantity:2,
            type:"Spice",
            price:34,
            image:"https://i.postimg.cc/jSKqSSdj/ginger.jpg"
        },
        {
            name:"Corriander",
            quantity:2,
            type:"Spice",
            price:34,
            image:"https://i.postimg.cc/XYyK4xqW/corriander.jpg"
        },
        {
            name:"Garlic",
            quantity:2,
            type:"Spice",
            price:34,
            image:"https://i.postimg.cc/B6Z1LCSX/garlic.jpg"
        },
        {
            name:"Spinach",
            quantity:3,
            type:"Vegetable",
            price:120,
            image:"https://i.postimg.cc/L4cLvLv0/spinach.jpg"
        },
        {
            name:"Terere",
            quantity:3,
            type:"Vegetable",
            price:90,
            image:"https://i.postimg.cc/43yYXxB9/terere.jpg"
        },
        {
            name:"Carrots",
            quantity:3,
            type:"Vegetable",
            price:100,
            image:"https://i.postimg.cc/Kv5jLMWT/carrots.png"
        },
        {
            name:"Coconut",
            quantity:3,
            type:"Fruit",
            price:100,
            image:"https://i.postimg.cc/fRvP7pT4/coconuts.jpg"
        },
        {
            name:"Dates",
            quantity:3,
            type:"Fruit",
            price:90,
            image:"https://i.postimg.cc/FsCdfs3w/dates.jpg"
        },
        {
            name:"Papaya",
            quantity:3,
            type:"Fruit",
            price:100,
            image:"https://i.postimg.cc/4x8DkjC6/papaya.jpg"
        }

    ];